name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: echo 'plan...'
  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Check Environment
        run: |
          if ! gh api /repos/${{ github.repository }}/environments/${{ inputs.environment }} >/dev/null 2>&1; then
            echo "Error: Environment '${{ inputs.environment }}' does not exist."
            exit 1
          fi
      - name:
        run: echo 'apply...'
