name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: echo 'plan...'
  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: approval
    steps:
      - name: Apply
        run: echo '${{ secrets.FOO }} ${{ vars.BAR }}'
