name: Deploy To production

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the deployment environment'
        required: true
        type: choice
        options:
          - develop
          - staging
          - production

permissions:
  id-token: write
  contents: read
jobs:
  deploy-dev:
    uses: can-be-to/approval-workflow-sample/.github/workflows/deploy.yml@feature/test
    with:
      environment: ${{ github.event.inputs.environment }}
