name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: plan
        run: echo 'plan...'

      - name: Wait manual approval
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ghRunListCmd="gh run list --workflow 'Approve ${{ inputs.environment }}' --branch ${{ github.ref_name }} \
              --status success --json headSha --jq '.[].headSha' --limit 1"

          isApproved=false
          until ${isApproved}; do
            sleep 10
            result=$(${ghRunListCmd})

            # github.shaが一致すればOK
            if [ "${{ github.sha }}" = "${result}" ]; then
              isApproved=true
            fi
          done

      - name: apply
        run: echo '${{ secrets.FOO }} ${{ vars.BAR }}'

# jobs:
#   plan:
#     runs-on: ubuntu-latest
#     steps:
#       - name:
#         run: echo 'plan...'
#   apply:
#     needs: plan
#     runs-on: ubuntu-latest
#     environment: approval
#     steps:
#       - name: Apply
#         run: echo '${{ secrets.FOO }} ${{ vars.BAR }}'
